server:
  port: 8090


spring:
  datasource:
    username: "macros_web_app"
    password: "DUQa3Rc#!0@v" ##Enter your root password
    url: "jdbc:sqlserver://db-cbol-apps-prod.database.windows.net;database=MacrosWEB;"
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
